"""Branch에 kakao_url, naver_place_url 추가

Revision ID: 1b59c5e41539
Revises: 723126c37cd1
Create Date: 2026-05-14 18:30:57.949401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b59c5e41539'
down_revision: Union[str, Sequence[str], None] = '723126c37cd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('kakao_url', sa.String(length=255), nullable=True))
    op.add_column('branches', sa.Column('naver_place_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'naver_place_url')
    op.drop_column('branches', 'kakao_url')
    # ### end Alembic commands ###
