"""락커/운동복 상품 도메인 + Member 락커·운동복 FK 교체

Revision ID: 95a190e83840
Revises: 7ab8256d01dd
Create Date: 2026-05-15 18:19:58.904991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95a190e83840'
down_revision: Union[str, Sequence[str], None] = '7ab8256d01dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clothes_passes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('cash_price', sa.Integer(), nullable=False),
    sa.Column('card_price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locker_passes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('cash_price', sa.Integer(), nullable=False),
    sa.Column('card_price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('members', sa.Column('locker_pass_id', sa.UUID(), nullable=True))
    op.add_column('members', sa.Column('clothes_pass_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'members', 'locker_passes', ['locker_pass_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'members', 'clothes_passes', ['clothes_pass_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('members', 'clothes_rental')
    op.drop_column('members', 'locker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('locker', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('members', sa.Column('clothes_rental', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_column('members', 'clothes_pass_id')
    op.drop_column('members', 'locker_pass_id')
    op.drop_table('locker_passes')
    op.drop_table('clothes_passes')
    # ### end Alembic commands ###
